#ifndef CONFIG_H
#define CONFIG_H

#define TARGET_FPS 60
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT WINDOW_WIDTH * 2
#define GRID_SQUARE_SIZE 65
#define GRID_WIDTH 10
#define GRID_HEIGHT 20
#define GRID_STARTING_X (WINDOW_WIDTH / 2) - (GRID_SQUARE_SIZE * GRID_WIDTH) / 2
#define GRID_STARTING_Y (WINDOW_HEIGHT / 2) - (GRID_SQUARE_SIZE * GRID_HEIGHT) / 2
#define GRID_WALL_RIGHT (GRID_STARTING_X + (GRID_WIDTH * GRID_SQUARE_SIZE))
#define GRID_FLOOR (GRID_STARTING_Y + (GRID_HEIGHT * GRID_SQUARE_SIZE))

#endif